- src/App.tsx
- src/pages/IntroPage.tsx
- src/sites/EdcSite.tsx
> Add basic layout for EdcSite

- src/sites/EdcSite.tsx
出现第一次进入电设页面菜单栏选项显示不正确的问题
增加selected状态使得第一次进入电设页面时跳转至主介绍页面
> Fix bug of selected menu key in EdcSite

- src/api/announcements.ts
- src/pages/EnrollPage.tsx
- src/pages/ResourcePage.module.css
- src/pages/ResourcePage.tsx
- src/sites/EdcSite.tsx
> Add Resource Page

- src/pages/ContestPage.module.css
- src/pages/ContestPage.tsx
- src/pages/DivisionPage.tsx
- src/sites/HomeSite.module.css
- src/sites/HomeSite.tsx
> Add ContestPage

- src/pages/ContestPage.tsx
"<br />"s  are in the wrong places
> Move all empty lines to its place

- package.json
- src/pages/EnrollPage.tsx
- src/pages/ResourcePage.tsx
- src/pages/TeamJoinPage.tsx
- src/pages/TeamManagePage.tsx
- yarn.lock
加入各页面关于不在报名时间的错误提示
资源页面开启dangerouslySetInnerHTML以方便后期加入链接等操作
> Error message update

- src/sites/EdcSite.tsx
> Fix router when visiting /thuedc/

- src/pages/TeamJoinPage.tsx
- src/redux/actions/teams.ts
> Change getTeams to asynchronized

- src/pages/TeamJoinPage.module.css
- src/pages/TeamJoinPage.tsx
- src/redux/reducers/teams.ts
- src/sites/EdcSite.tsx
Fixed:
- 队伍加载时fetching被错误地置为false
- 修改页面显示数量改变时未改变totalTeams
- CSS导致显示不全
Add:
- 队伍人满时加入按钮disabled===true
> 🐛 Fix bugs in TeamJoinPage

- package.json
- src/pages/TeamJoinPage.tsx
- yarn.lock
增加`root`与`organizer`角色的队伍信息导出功能
> Add export button for teams info

- src/pages/TeamJoinPage.tsx
- src/redux/actions/teams.ts
昨晚错误地将`playerInfoPair`打成`playersInfo`，导致前端获得的leaderInfo为undefined
现已解决
> 🐛 Fix wrong code in getting players' info

- src/api/postgraduate.graphql
- src/api/types.ts
- src/pages/InfoSite/PostgraduateMentorPage.tsx
- 加入了删除信息的功能
- 使得没有操作权限的用户不能在前端看到对应的操作按钮
> Add deleteInfo & fix access loopholes

- package.json
- src/styled-component-env.d.ts
- yarn.lock
> :arrow_up::label: declare cssprop explicitly to upgrade @types/react

- src/api/types.ts
- src/pages/InfoSite/PostgraduateMentorPage.tsx
> Change Frontend intend/in_contact/confirmed

- src/api/postgraduate.graphql
- src/api/types.ts
- src/pages/InfoSite/PostgraduateMentorPage.tsx
> ✨ Add modal for EEsenior to see applications varified or not and delete applications

- src/api/postgraduate.graphql
- src/api/types.ts
- src/pages/InfoSite/MentorInfoVerifyPage.tsx
- src/pages/InfoSite/PostgraduateApplicationPage.tsx
- src/pages/InfoSite/PostgraduateMentorPage.tsx
- src/pages/InfoSite/index.tsx
- 只有已确认需要审核
- 加入刷新按钮
- 后端修复无法删除申请的权限问题
> Fix several bugs

- src/configs/index.ts
> Add salutation of scholarships and aids

- .gitignore
- src/App.tsx
> add link to logo and EESAST

- src/api/info_mentor.graphql
- src/api/types.ts
- src/pages/InfoSite/MentorApplicationPage.tsx
- Allow student to delete application
- Allow teacher to reject application
> feat(mentor): Add delete & reject

- src/api/types.ts
- src/pages/ThuaiSite/BattlePage.tsx
> battlepage回放

- src/pages/ThuaiSite/BattlePage.tsx
> battlepage提交代码后输入框自动清空

- src/pages/ThuaiSite/BattlePage.tsx
- src/pages/ThuaiSite/JoinPage.tsx
- src/pages/ThuaiSite/ManagePage.tsx
- src/pages/ThuaiSite/RegisterPage.tsx
修改battlepage：增添了发起对战成功的提示
修改registerpage、joinpage、managepage：使队伍人员无法变更（加入、退出、解散队伍），无法组建新的队伍
> 增添了发起对战成功的提示，使队伍人员无法再变更、无法再组新的队伍

- src/pages/ThuaiSite/BattlePage.tsx
将playback的后缀改为roomid+.thupb
并且加回代码展示（此处加回的原因为每队都已有代码数据在数据库）
> add playback 后缀

- src/pages/ThuaiSite/BattlePage.tsx
> 后缀修正为thuaipb

- src/pages/ThuaiSite/BattlePage.tsx
> 新增对战选择 白方 紫方功能

- src/App.tsx
- src/pages/InfoSite/MentorApplicationPage.tsx
fix(mentor): 申请时间格式调整
feat:(mentor) 添加删除申请确认框
> fix & feat

- package.json
- src/app/ContestSite/CodePage.tsx
- src/app/ContestSite/ResourcePage.tsx
- src/app/InfoSite/MentorApplicationPage.tsx
- src/app/InfoSite/NoticePage.tsx
- yarn.lock
在CodePage.tsx等4个文件中修改了RcCustomRequestOptions的import来源；e.onSuccess等函数增加非空断言，同时修改了参数类型。
> fix: antd从4.9.4升级至4.10.0

- .env
- src/app/ContestSite/ArenaPage.tsx
- src/app/ContestSite/CodePage.tsx
- src/app/ContestSite/JoinPage.tsx
- src/app/ContestSite/ManagePage.tsx
- src/app/ContestSite/ManageTeamsPage.tsx
- src/app/ContestSite/RegisterPage.tsx
- src/generated/graphql.tsx
- src/graphql/contest/contest.graphql
> fix: 修改了contest_team_member部分的graphql

- src/app/ShareSite/IntroPage.tsx
- src/app/ShareSite/MinecraftPage.tsx
- src/app/ShareSite/index.tsx
> feat(Share): add IntroPage & MinecraftPage

- src/api/hooks/user.ts
- src/app/Components/Authenticate.tsx
- src/app/UserSite/index.tsx
- src/app/index.tsx
> feat(user): user.isLoggedIn!!!!

- src/api/cos.ts
格式一是应该是当过了ExpiredTime才会刷新！
格式二设置ScopeLimit遇到不同请求的时候才会重新调用！
另外还可以把options.Scope传给后端，这样可以用啥给啥。
~~一杯茶，一包烟，一行代码调一天~~
> Update cos.ts ScopeLimit!!!!!!!!!!

- src/app/ContestSite/ArenaPage.tsx
- src/app/ContestSite/CodePagesource.tsx
- src/generated/graphql.tsx
- src/graphql/contest/team_code.graphql
由于setOpponentTeamId状态更新是异步的，点击队伍之后还是会有延迟，还没想好如何解决
> fix: rewrite arenapage codes and add player code manager

- docs/contest.md
- src/app/ContestSite/RecordPage.tsx
> fix: add room_status "Timeout"

- src/app/ShareSite/CoursePage/CourseRating.tsx
- src/app/ShareSite/CoursePage/DiscussDrawer.tsx
- src/app/ShareSite/CoursePage/index.tsx
1. 加了讨论按钮的徽标（小红点）
2. 修复useEffect里handleCourseComment一直发请求的问题
3. 修改文件结构（与其他页面统一）
> fix: add badge and fix file structure

- src/app/ContestSite/IntroPage.tsx
- src/app/ContestSite/TeamPage/ManagePage.tsx
- src/app/ShareSite/CoursePage/DiscussDrawer.tsx
- src/app/ShareSite/CoursePage/index.tsx
- src/app/UserSite/ProfilePage.tsx
目前的筛选逻辑写在前端，我尝试了一下似乎无法用graphql语句实现（
> fix bugs in course search

- src/app/ShareSite/WeeklyPage.tsx
- src/index.css
> fix: mobile layout error
